<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NetfxLibvirt</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DevTunnels.Ssh" Version="3.12.42" />
    <PackageReference Include="Microsoft.DevTunnels.Ssh.Keys" Version="3.12.42" />
    <PackageReference Include="Microsoft.DevTunnels.Ssh.Tcp" Version="3.12.42" />
  </ItemGroup>

</Project>
